name: phone_proxy
description: "Example app for phone proxy piece of BLE-SOCKS bridge."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  viam_sdk: ^0.0.1
  cupertino_icons: ^1.0.6
  permission_handler: ^11.3.1
  socks5_proxy: ^1.0.6
  # `blev` is Viam's underlying library for BLE-SOCKS interactions (called
  # `flutter-ble` on github). We recommend that you do not interface with the
  # library directly and instead use a copy of the API exposed in this example
  # app.
  blev: ^0.0.4
  logger: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
