[package]
name = "rust_viam_server"
version = "0.1.0"
edition = "2021"

[dependencies]
bluer = { version = "0.17.2", features = ["bluetoothd", "l2cap"] }
futures = "0.3.30"
tokio = "1.38.0"
uuid = "1.9.1"
